### ISSUE TITLE
Password required to change profile?

### ISSUE THREAD

**Issue by joaoherberto** [slimbook/slimbookbattery-translations#21]
I compiled this in from the AUR and works very well, but is there a way to have it not ask for a password every time I decide to change the profile?

**Comment by slimbook** [comment]
We have not developed this option, but it would be interesting.

**Comment by opennomad** [comment]
This could be related to polkit, which is what was doing it on Ubuntu. I wrote up a workaround here: https://opennomad.com/2021/03/14/slimbookbattery-and-the-frequent-password-prompt-on-ubuntu/

**Comment by slimbook** [comment]
> This could be related to polkit, which is what was doing it on Ubuntu. I wrote up a workaround here: https://opennomad.com/2021/03/14/slimbookbattery-and-the-frequent-password-prompt-on-ubuntu/

Great! we will implement this.
Thank you very much.
